import type { ReactNode } from "react";

export interface ClientManifest {
    /**
     * Map of routeId to dynamic import functions.
     * In a real framework, this would be generated by a bundler plugin.
     * example: { "/blog/[slug]": { page: () => import("/app/blog/[slug]/page.tsx"), layouts: [...] } }
     */
    routes: Record<
        string,
        {
            page: () => Promise<any>;
            layouts: (() => Promise<any>)[];
        }
    >;
}

export interface RouterState {
    url: string;
    routeId: string;
    data: any;
    pageParams: Record<string, string>;
    PageComponent: any | null;
    LayoutComponents: any[];
}
