name: FlowJS CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # pnpm автоматически прочитает версию из packageManager в package.json
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Настраиваем Node.js и включаем кэширование зависимостей
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Framework Packages
        run: pnpm run build

      - name: Run Typecheck
        run: pnpm run typecheck

      - name: Run Lint
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test

      - name: Build Example App
        working-directory: ./examples/basic
        run: pnpm run build

      - name: Smoke Test Example App
        working-directory: ./examples/basic
        run: |
          pnpm run start &
          sleep 5
          curl -f http://localhost:3000 || exit 1
          curl -f http://localhost:3000/api/hello || exit 1
          kill %1